name: jobs examples
on:
  push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: correction command
        run: echo Hello, world! Build ok.
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: step do deploy
        run: echo Hello, world! Deploy.
